plugins:
  # Consumers first
  #- path: hologram/
  - path: open_vins/
  - path: imu_integrator/
  - path: pose_prediction/
  - path: timewarp_gl/
  - path: offload_data/
  - path: audio_pipeline/
  # Producers last
  #- path: zed/
  - path: offline_imu_cam/
  # - path: ground_truth_slam/
#data: zip+http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip?path=mav0
data: ../data1/
demo_data: ../demo_data/
output_data: ../output_data/
loader:
  name: monado
  monado:
    path: ../monado_integration
    config:
      ILLIXR_PATH: ../../ILLIXR
  openxr_app:
    path: "../OpenXR-Apps/sponza/bin/sponza.x86_64"
    config: {}
profile: opt
